# Generated by Django 3.0.4 on 2021-01-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210118_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('permiso_desde_codigo', 'Esto es un permiso creado desde código'), ('segundo_permiso_codigo', 'Esto es un permiso creado desde código')]},
        ),
    ]
