# Generated by Django 3.0.4 on 2021-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='libros/', verbose_name='Imagen'),
        ),
    ]
